# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        pyramid-version: ["<2", ">=2"]
        redis-version: ["<4", ">=4.0.0"]
        exclude:
          # Pyramid 2 doesn't support Python 2.7 or 3.5
          - python-version: 2.7
            pyramid-version: ">=2"
          # Redis 4.0 require python3.6 or higher
          - python-version: 2.7
            redis-version: ">=4.0.0"

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[testing]" "pyramid${{ matrix.pyramid-version }}"
        pip install ".[testing]" "redis${{ matrix.redis-version }}"
        pip freeze
    - name: Test with pytest
      run: |
        # Python 3.5 needs PYTHONHASHSEED to succeed.
        PYTHONHASHSEED='3963681585' pytest
